- name: Upgrade minor version of Jetpack
  ansible.builtin.apt:
    upgrade: dist

- name: Install Jtop
  ansible.builtin.pip:
    name: "jetson-stats==4.3.2"
    executable: pip3

# - name: Set jetson power mode to highest performance (NVP_model)
#   ansible.builtin.shell:
#     cmd: sudo nvpmodel -m 0

- name: Configure tc modules for network emulation
  block:
    - name: Copy pre-built kernel modules
      ansible.builtin.copy:
        src: jetson_tc_kernel_modules/{{ ansible_kernel }}/
        dest: "/lib/modules/{{ ansible_kernel }}/kernel/"
        mode: '0644'

    - name: Reload kernel modules if changed
      ansible.builtin.command: "depmod -a"

    - name: Load kernel modules from list
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - ifb
        - sch_netem
        - sch_tbf

    - name: Ensure modules are loaded on boot
      ansible.builtin.copy:
        content: |
          ifb
          sch_netem
          sch_tbf
        dest: /etc/modules-load.d/tc_modules.conf
        mode: '0644'
