- name: Ensure standard dataset path exists
  ansible.builtin.file:
    path: "{{ std_datasets.dest_path }}"
    state: directory
    owner: root
    group: root
    mode: '0555'

- name: Push standard datasets to device
  ansible.posix.synchronize:
    src: "{{ std_datasets.src_path }}"
    dest: "{{ std_datasets.dest_path }}"

- name: Ensure dataset path for pytorch/hf datasets exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0775'
  loop:
    - "{{ pytorch_datasets.path }}"
    - "{{ hf_datasets.path }}"
