project: colext_example
job_name: "SOTA FL experiment"

code:
  client:
    command: >-
      python3 ./client.py
      --flserver_address=${COLEXT_SERVER_ADDRESS}
  server:
    command: >-
      python3 ./server.py
      --num_clients=${COLEXT_N_CLIENTS}
      --num_rounds=3

clients:
  - dev_type: LattePandaDelta3
    count: 4
    add_args: "--max_step_count=100"

  - dev_type: JetsonOrinNano
    count: 2
    add_args: "--max_step_count=200"

  - dev_type: OrangePi5B
    count: 8
    add_args: "--max_step_count=50"

  - dev_type: JetsonAGXOrin
    count: 2
    add_args: "--max_step_count=200"

  - dev_type: JetsonXavierNX
    count: 2
    add_args: "--max_step_count=200"

  - dev_type: JetsonNano
    count: 6
    add_args: "--max_step_count=100"

# Monitoring defaults
monitoring:
  scraping_interval: 0.2 # in seconds
  live_metrics: True # True/False
