apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: rabbitmq-system
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 31672
    name: management