{
 "title": "CoLExT dashboard",
 "time": { "from": "2024-05-28T08:25:19.983Z", "to": "2024-05-28T08:30:55.633Z" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT project_name\nFROM projects p\nWHERE EXISTS (\n    SELECT 1\n    FROM jobs j\n    WHERE j.project_id = p.project_id\n);"
   },
   {
    "name": "jobid",
    "label": "JobID",
    "query": "SELECT job_id \nFROM jobs\nJOIN projects USING(project_id)\nWHERE  (${show_incomplete_jobs} OR (end_time IS NOT NULL))\nAND project_name = 'unnamed';"
   },
   {
    "name": "round_n",
    "label": "Rounds",
    "query": "SELECT round_number \nFROM rounds\nWHERE  job_id = ${jobid}\nAND round_number > 0;"
   },
   {
    "name": "clientid",
    "label": "ClientID",
    "query": "select client_number from fl_testbed_logging.clients where job_id = ${jobid}"
   },
   { "name": "show_incomplete_jobs", "label": "Show incomplete jobs", "query": "True, False" },
   { "name": "show_stages", "label": "Show stages", "query": "True, False" }
  ]
 },
 "panels": [
  {
   "title": "Aggregated accuracy ",
   "type": "trend",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT round_number, dist_accuracy\nFROM rounds\nWHERE job_id = ${jobid}\nORDER BY round_number ASC;"
    }
   ]
  },
  {
   "title": "Server Accuracy ",
   "type": "trend",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT round_number, srv_accuracy\nFROM rounds\nWHERE job_id = ${jobid}\nORDER BY round_number ASC;"
    }
   ]
  },
  { "title": "HW Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH time_bounds AS (\n    SELECT MIN(start_time) as start_time, MAX(end_time) as end_time\n    FROM rounds\n    WHERE job_id = ${jobid}\n      AND round_number in ($round_n)\n)\nSELECT time, \n    gpu_util, \n    cpu_util, \n    power_consumption,\n    mem_util,\n    n_bytes_rcvd,\n    n_bytes_sent,\n    net_usage_in,\n    net_usage_out,\n    concat('Client ', cast(client_number as text), ' (', devices.device_name,')')\nFROM clients as clients\n  JOIN device_measurements USING(client_id)\n  JOIN jobs USING(job_id)\n  JOIN devices USING(device_id)\nWHERE job_id = ${jobid}\n  AND client_number in ($clientid)\n  -- AND time >= (SELECT start_time FROM time_bounds)\n  -- AND time <= (SELECT end_time FROM time_bounds)\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Memory utilization (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Network usage in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Network usage out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  { "title": "AVG Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "GPU utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name,\n  AVG(gpu_util) as avg_value\nFROM\n  clients as clients\n  JOIN device_measurements USING (client_id)\n  JOIN jobs USING (job_id)\n  JOIN devices USING(device_id)\nWHERE\n  job_id = ${jobid}\n  AND client_number in ($clientid)\n  AND time >= start_time\nGROUP BY\n  device_name\nORDER BY\n  device_name"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name,\n  AVG(cpu_util) as avg_value\nFROM\n  clients as clients\n  JOIN device_measurements USING (client_id)\n  JOIN jobs USING (job_id)\n  JOIN devices USING(device_id)\nWHERE\n  job_id = ${jobid}\n  AND client_number in ($clientid)\n  AND time >= start_time\nGROUP BY\n  device_name\nORDER BY\n  device_name"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name,\n  AVG(power_consumption) as avg_value\nFROM\n  clients as clients\n  JOIN device_measurements USING (client_id)\n  JOIN jobs USING (job_id)\n  JOIN devices USING(device_id)\nWHERE\n  job_id = ${jobid}\n  AND client_number in ($clientid)\n  AND time >= start_time\nGROUP BY\n  device_name\nORDER BY\n  device_name"
    }
   ]
  },
  {
   "title": "Network rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name,\n  AVG(CASE WHEN net_usage_in > 1024*1024 THEN net_usage_in ELSE NULL END) as \"Rcv\",\n  AVG(CASE WHEN net_usage_out > 1024*1024 THEN net_usage_out ELSE NULL END) as \"Sent\"\nFROM\n  clients as clients\n  JOIN device_measurements USING (client_id)\n  JOIN jobs USING (job_id)\n  JOIN devices USING(device_id)\nWHERE\n  job_id = ${jobid}\n  AND client_number in ($clientid)\n  AND time >= start_time\nGROUP BY\n  device_name\nORDER BY\n  device_name"
    }
   ]
  },
  {
   "title": "Communicated bytes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name,\n  AVG(n_bytes_rcvd) as \"Rcv\",\n  AVG(n_bytes_sent) as \"Sent\"\nFROM\n  clients as clients\n  JOIN device_measurements USING (client_id)\n  JOIN jobs USING (job_id)\n  JOIN devices USING(device_id)\nWHERE\n  job_id = ${jobid}\n  AND client_number in ($clientid)\n  AND time >= start_time\nGROUP BY\n  device_name\nORDER BY\n  device_name"
    }
   ]
  },
  {
   "title": "Memory Utilization (RSS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name,\n  AVG(mem_util) as \"memory\"\nFROM\n  clients as clients\n  JOIN device_measurements USING (client_id)\n  JOIN jobs USING (job_id)\n  JOIN devices USING(device_id)\nWHERE\n  job_id = ${jobid}\n  AND client_number in ($clientid)\n  AND time >= start_time\nGROUP BY\n  device_name\nORDER BY\n  device_name"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Logs ",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{namespace=\"default\", colext_job_id=\"$jobid\", pod=\"fl-server\", container=\"fl-server\"} |= ``"
      }
     ]
    },
    {
     "title": "Client ${clientid} logs ",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "repeat": "clientid",
     "targets": [
      {
       "expr": "{namespace=\"default\", colext_job_id=~\"$jobid\", pod=~\"client-($clientid)\", container=\"fl-client\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}