project: colext_example # project name should not have spaces
job_name: "SOTA FL experiment"

code:
  client:
    command: >-
      python3 ./client.py
      --flserver_address=${COLEXT_SERVER_ADDRESS}
  server:
    command: >-
      python3 ./server.py
      --num_clients=${COLEXT_N_CLIENTS}
      --num_rounds=3

clients:
   - dev_type: LattePandaDelta3
     count: 2
     add_args: "--max_step_count=50"

  - dev_type: JetsonOrinNano
    count: 2
    add_args: "--max_step_count=200"

  - dev_type: OrangePi5B
    add_args: "--max_step_count=100"

  - dev_type: OrangePi5B
    count: 2
    add_args: "--max_step_count=50"

  # - { dev_type: JetsonAGXOrin,  count: 1 }
  # - { dev_type: JetsonOrinNano, count: 2 }
  # - { dev_type: JetsonXavierNX, count: 2 }
  # - { dev_type: JetsonNano, count: 6 }

# Monitoring defaults
# monitoring:
#   live_metrics: True # True/False
#   push_interval: 10 # in seconds
#   scraping_interval: 0.3 # in seconds
